name: Check staged model

on:
  repository_dispatch:
    types: [staged_model]

jobs:
  identify_event:
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.set_output.outputs.model_name }}
    steps:
      - name: Setting model environment variable and output
        id: set_output
        run: |
          MODEL_PATH="${{ github.event.client_payload.artifact_version_string }}"
          echo "model_name=$MODEL_PATH" >> $GITHUB_OUTPUT

  test_model:
    runs-on: ubuntu-latest
    needs: identify_event
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
      MODEL_NAME: ${{ needs.identify_event.outputs.model_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Test model performance
        run: |
          PYTHONPATH=. uv run pytest tests/performancetests/test_model.py

  add_production_alias:
    runs-on: ubuntu-latest
    needs: [identify_event, test_model]
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --dev --locked
        
      - name: Add production alias
        run: |
          uv run python link_model.py "${{ needs.identify_event.outputs.model_name }}" --aliases production